export const SET_VISIBLE = 'SET_VISIBLE';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
export const SET_CHECKING_VISIBLE = 'SET_CHECKING_VISIBLE';
export const GET_CARTS_DATA = 'GET_CARTS_DATA';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_ENTRY_SEARCH_BTN = 'SET_ENTRY_SEARCH_BTN';
export const SET_DELETE_STORE = 'SET_DELETE_STORE';