export const SET_VISIBLE = 'SET_VISIBLE';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
export const SET_CHECKING_VISIBLE = 'SET_CHECKING_VISIBLE';
export const GET_CARTS_DATA = 'GET_CARTS_DATA';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';